@echo off
echo downloading jre...
curl "https://cdn.azul.com/zulu/bin/zulu8.84.0.15-ca-jre8.0.442-win_x64.zip" --output jre8.zip
echo downloading minecraft 1.2.5 server.jar...
curl "https://piston-data.mojang.com/v1/objects/d8321edc9470e56b8ad5c67bbd16beba25843336/server.jar" --output server.jar
echo writing readme...
echo Packaged into an exe by rust-java-bundler. github.com/amir16yp/rust-java-bundler > README.txt
echo Creating rust project...
python.exe ..\java-bundler-rust.py --output "%cd%" --name MinecraftServer --jar server.jar --jre .\jre8.zip --files README.txt
pause